packaging_format = 2

id = "continuwuity"
name = "Continuwuity"
description.en = "Simple, fast and reliable chat server powered by Matrix based on Conduit and Conduwuit"
description.fr = "Serveur de chat simple, rapide et fiable alimenté par Matrix"

version = "0.5.5~ynh1"

maintainers = []

[upstream]
license = "Apache-2.0"
website = "https://continuwuity.org/"
admindoc = "https://forgejo.ellis.link/continuwuation/continuwuity"
code = "https://forgejo.ellis.link/continuwuation/continuwuity"

[integration]
yunohost = ">= 12.1.9"
helpers_version = "2.1"
architectures = [ "arm64", "amd64" ]
multi_instance = false

ldap = true

sso = true

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"
    help.en = "If you want to be able to federate with other servers, you should let the default choice, visitors"
    help.fr = "Si vous souhaitez pouvoir fédérer votre serveur avec d'autres, vous devez laisser le choix par défaut, visiteurs"

    [install.server_name]
    ask.en = "Select the display name for your Continuwuity server"
    ask.fr = "Sélectionnez le nom d'affichage pour votre serveur Continuwuity"
    help.en = "If you choose domain.tld, your Matrix user-ids will be looking like @user:domain.tld instead of @user:continuwuity.domain.tld"
    help.fr = "Si vous choisissez domain.tld, vos identifiants Matrix ressembleront à @utilisateur:domain.tld plutôt que @utilisateur:continuwuity.domain.tld"
    type = "domain"

    [install.registration]
    ask.en = "Should the server allow any visitor to register as a user?"
    ask.fr = "Le serveur doit-il permettre à quiconque de s'enregistrer comme utilisateur ?"
    type = "boolean"
    help.en = "If no, accounts should be registered by an admin after defining a secret. If yes, to protect your server and the federation from spammer, federation will be deactivated by default. You must Activate CAPTCHA verification before federation reactivation. See Config Panel for instructions"
    help.fr = "Si non, les comptes seront créés par un admin après avoir défini un secret. Si oui, la fédération sera désactivée pour protéger la fédération et vous des spammeurs. Activez la vérification par CAPTCHA avant de réactiver la fédération ! Voir les instructions dans le Config Panel"
    default = false

[resources]

    [resources.sources]

        [resources.sources.main]
        in_subdir = false
        extract = false
        format = "bin"
        rename = "continuwuity"
        amd64.url = "https://forgejo.ellis.link/continuwuation/continuwuity/releases/download/v0.5.5/conduwuit-haswell-linux-amd64-maxperf"
        amd64.sha256 = "f5fa8a91503d1cb026ac2745d610dda7e8921f0e8273c0e8b45700e57ac2d3af"
        arm64.url = "https://forgejo.ellis.link/continuwuation/continuwuity/releases/download/v0.5.5/conduwuit-linux-arm64-maxperf"
        arm64.sha256 = "deb73a7ee010e2817174230fca1c48dd915e7ab0f963448d9cf9175dbb4dcf03"
        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.arm64 = "^conduwuit-haswell-linux-amd64-maxperf$"
        autoupdate.asset.amd64 = "^conduwuit-linux-arm64-maxperf$"

[resources.system_user]

[resources.install_dir]

[resources.permissions]
main.url = "/"
main.show_tile = false

server_api.url = "__DOMAIN__/_matrix"
server_api.label = "Server access for client apps."
server_api.show_tile = false
server_api.allowed = "visitors"
server_api.auth_header = false
server_api.protected = true

server_client_infos.url = "__SERVER_NAME__/.well-known/matrix"
server_client_infos.label = "Server info for federation. (well-known)"
server_client_infos.show_tile = false
server_client_infos.allowed = "visitors"
server_client_infos.auth_header = false
server_client_infos.protected = true

admin.show_tile = false
admin.allowed = "admins"
admin.label = "Continuwuity served admin"

[resources.ports]
main.default = 6167
